### ISSUE TITLE
Integrate the payment and receipt managers into the go-nitro client.

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#775]
(If following a TDD approach this follows #773 and is then all about making the failing "payment integration" test pass)

We’ve implemented a PaymentManager and a ReceiptManager  #800 .

The “user story” would look something like

- [ ] https://github.com/statechannels/go-nitro/issues/794 Alice, Bob and Irene create a virtual channel. Once opened, Alice creates a PaymentManager and Bob creates a ReceiptManager.
- [x] https://github.com/statechannels/go-nitro/issues/793: : Alice sends a stream of vouchers to Bob
- [ ] https://github.com/statechannels/go-nitro/issues/795 Alice, Bob or Irene trigger the virtual channel to close. The channel is defunded and ledgers rebalanced according to the "largest" voucher signed by Alice.
- [x] https://github.com/statechannels/go-nitro/issues/772
- [ ] https://github.com/statechannels/go-nitro/issues/822
- [x] https://github.com/statechannels/go-nitro/issues/823
- [ ] #827 
- [x] #837

**Comment by lalexgap** [comment]
I'm closing this as the bulk of the work is done. There are still some remaining things to be done but they can be tracked under the payments label.
